### ISSUE TITLE
Hatch Rest+ support 

### ISSUE THREAD

**Issue by jamescadd** [dahlb/ha_hatch#1]
Thanks for adding this! Do you happen to know if the Rest+ would be supported?

**Comment by dahlb** [comment]
I assume the sound machine of rest+ would be supported but I didn't add any of the light features.  

I don't have a rest+ so i can't verify, but based on the reference implementation I used from node that is my expectation.

**Comment by manofpants** [comment]
I second the thanks! Really cool integration for an obscure product. I'm wondering also about Rest (not +) and the Restore. Going to play around with this now.

**Comment by markmghali** [comment]
I am also wondering about the Hatch Rest as well! I know it only has Bluetooth LE so it might be tricky. I did see a project that was trying to get the info through an esp32 and send it over wifi. ESPhome and hatch would be killer!

**Comment by niemyjski** [comment]
I'd be willing to test out any changes for the rest+

**Comment by rml1111** [comment]
I would also be willing to test out changes for the Rest+. I currently am able to control my Rest+ sound machines/nightlights from Home Assistant through Homebridge, but ideally would like to be able to control natively and eliminate the need for this workaround. I have limited software development skills, but am glad to work on this with anyone who is interested.

**Comment by jamescadd** [comment]
I still haven't tested it. I was wondering if the newly announced Bluetooth and HomeKit support makes it easier to use Rest+ from HA?

**Comment by rml1111** [comment]
Rest+ connects via wifi (I think the Rest is bluetooth). However, I need to learn more about the new HomeKit support and will post back with findings. As mentioned in my previous comment, my Rest+'s are currently connected to HomeAssistant via HomeBridge (which is essentially emulated HomeKit).

**Comment by dahlb** [comment]
I got a rest+ for a beach trip, I've added the sound functionality https://github.com/dahlb/ha_hatch/commit/5571cc2be357131fca9646f702f227b5c52be0fb and hope to have the light added later this weekend

**Comment by dahlb** [comment]
light support added, https://github.com/dahlb/ha_hatch/commit/70f61d74250849a1cc8997959ade0b0d6d3afa80

**Comment by niemyjski** [comment]
Amazing! I wonder if there is a scenes api.

**Comment by dahlb** [comment]
wifi connectivity and battery level sensors added
