### ISSUE TITLE
Magic number depreciation

### ISSUE THREAD

**Issue by dbolton** [dahlb/ha_hatch#107]
Love this integration. It works great. 

I received the following log regarding depreciated and didn't see an existing bug report

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1520
First occurred: January 30, 2024 at 8:36:25 PM (1 occurrences)
Last logged: January 30, 2024 at 8:36:25 PM

Entity None (<class 'custom_components.ha_hatch.riot_media_entity.RiotMediaEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.VOLUME_SET|VOLUME_STEP|STOP|PLAY|SELECT_SOUND_MODE: 87044>, please create a bug report at https://github.com/dahlb/ha_hatch/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by dahlb** [comment]
thanks for writing this up, fixed in v1.17.1
