### ISSUE TITLE
Add Integration form missing email/password labels

### ISSUE THREAD

**Issue by tpansino** [dahlb/ha_hatch#11]
Screenshot of the form I see when I go to add a new integration:
![image](https://user-images.githubusercontent.com/2768420/192125255-fb6f8af4-dfa6-463a-9ed4-6d37153c2d23.png)

(I'm not sure what's wrong. I checked the `config_flow.py` against a similar integration that does have the labels, and they seem roughly the same.)

**Comment by dahlb** [comment]
fixed in https://github.com/dahlb/ha_hatch/commit/7b9b97d8e2d077a744bf5ab879cc8209d6bb3485 available in version 1.8.0
