### ISSUE TITLE
Light Entity stays on after manually turning off

### ISSUE THREAD

**Issue by chelupa** [dahlb/ha_hatch#119]
After Hatch Sleep app update, whenever I manually turn off the Rest+ (2nd Gen), the HA entity doesn't get updated that it's turned off. If I reload the integration, it will then recognize that it's off, but that will also turn off the light/sound

**Comment by tmeekes** [comment]
Same problem here. Seems that HA disconnects from the hatch server at some point and stops receiving polling updates. Requires an integration reload to resolve.

Only thing that I've noticed in the logs is an "unload entry" process... which then either seems to cause an mqtt disconnect or a credentials update.

**Comment by dahlb** [comment]
was this fixed by the ui threading issue fixed in 1.17.3?

**Comment by tmeekes** [comment]
Just installed it, so I'll report back in after testing it a bit!

**Comment by tmeekes** [comment]
So far the update seems to have resolved my problem.

**Comment by tmeekes** [comment]
This was working fine, but it seems broken with the latest update again...

**Comment by tmeekes** [comment]
This was working fine, but it seems broken with the latest update again...
