### ISSUE TITLE
HA 2024.5.0 deprecation warning

### ISSUE THREAD

**Issue by Intecpsp** [dahlb/ha_hatch#129]
1. `Detected that custom integration 'ha_hatch' calls async_write_ha_state from a thread at custom_components/ha_hatch/rest_media_entity.py, line 77: self.async_write_ha_state(), please report it to the author of the 'ha_hatch' custom integration`
2. `Detected that custom integration 'ha_hatch' calls async_write_ha_state from a thread at custom_components/ha_hatch/rest_light_entity.py, line 35: self.async_write_ha_state(), please report it to the author of the 'ha_hatch' custom integration`

Looks like it is rotating through the different instances of `async_write_ha_state`. I've also seen one for switch.py line 41

**Comment by gullygossner** [comment]
Similar issues on my end.

**Comment by dahlb** [comment]
1.17.2 resolves this warning that was caused by the websocket thread updating the home assistant ui directly

**Comment by Intecpsp** [comment]
1.17.2 does not fix this issue

**Comment by Intecpsp** [comment]
I noticed 1.17.2 didn't remove/update the call(s) this error was mentioning. I found [this](https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238), hope it's helpful.

**Comment by dahlb** [comment]
1.17.3 is updated based on the advice from @Intecpsp, much easier solution :)

**Comment by Intecpsp** [comment]
That seems to have fixed the issue! But the UI seems to be slow to show the changes. 

Before this change it didn't update until a page refresh. After this update it seems to update without a refresh, but takes a couple seconds to show the change.
