### ISSUE TITLE
Hatch broken after most recent upgrade

### ISSUE THREAD

**Issue by FastHowTo** [dahlb/ha_hatch#137]
Hatch was working mostly fine, but after I upgraded it in HACS, it is now broken, failing with the following:

Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 12:24:29 (3 occurrences)
Last logged: 12:24:33

Unable to install package hatch_rest_api==1.25.1: ERROR: Ignored the following versions that require a different python version: 1.24.1 Requires-Python <4,>=3.12.0; 1.25.0 Requires-Python <4,>=3.12.0; 1.25.1 Requires-Python <4,>=3.12.0 ERROR: Could not find a version that satisfies the requirement hatch_rest_api==1.25.1 (from versions: 1.6.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.1, 1.15.2, 1.16.0, 1.17.0, 1.18.0, 1.18.1, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.20.4, 1.20.5, 1.20.6, 1.20.8, 1.20.9, 1.20.10, 1.21.0, 1.22.0, 1.23.0, 1.24.0) ERROR: No matching distribution found for hatch_rest_api==1.25.1

I tried to delete and re-add the integration, and it fails with error 500 before even presenting the login dialogue.

**Comment by dahlb** [comment]
this is a compatibility with this integration and older versions of ha, newer versions of this integration are designed to the latest version of ha and ha expects python 3.12 since 2024.2 https://community.home-assistant.io/t/2024-2-more-voice-more-icons-more-integrations-more-everything/686359

**Comment by FastHowTo** [comment]
So the solution was to just let it break without warning?  Classy.
