### ISSUE TITLE
Add support for media player entity on/off states for rest plus 2nd gen

### ISSUE THREAD

**Issue by talormanda** [dahlb/ha_hatch#163]
Not sure if this is a limitation of HA or not. But even though my Rest device is "idle". It's showing in blue as an active speaker as if I am playing audio on it.

![image](https://github.com/user-attachments/assets/a3f10dfa-9acb-4c49-a39a-80541d3cf292)
![image](https://github.com/user-attachments/assets/b7daa7e4-0223-4510-b1e9-c811e0c117d7)

**Comment by dahlb** [comment]
My guess is your rest is on/light on; the blue I think represents power status not playing status

**Comment by talormanda** [comment]
> My guess is your rest is on/light on; the blue I think represents power status not playing status

![20240911_153453](https://github.com/user-attachments/assets/8938cfd1-99e6-438f-a5ac-f24d3c3864d8)

It's definitely off.

**Comment by dahlb** [comment]
I'll try to see what status the platform is using to determine that blue color

**Comment by talormanda** [comment]
> I'll try to see what status the platform is using to determine that blue color

Thanks. As a background. I've been using this for many months and it's always blue no matter what status the speaker is in.

**Comment by dahlb** [comment]
I released this feature in version 1.22.0, however I don't think this is a very good interface for the rest device. 1.23.0 will be back to blue.

when you support off ha prevents you from selecting a sound mode until you turn it on, in the hatch's case turning it on involves either turning on a light or starting a sound mode so I think having it idle instead of off provides a better user interface for the hatch.  Sorry that results in it being blue, but what that really represents is that it can start playing directly without having to be turned on first.

**Comment by talormanda** [comment]
> I released this feature in version 1.22.0, however I don't think this is a very good interface for the rest device. 1.23.0 will be back to blue.
> 
> when you support off ha prevents you from selecting a sound mode until you turn it on, in the hatch's case turning it on involves either turning on a light or starting a sound mode so I think having it idle instead of off provides a better user interface for the hatch. Sorry that results in it being blue, but what that really represents is that it can start playing directly without having to be turned on first.

Well that's unfortunate. There's no way to add a configuration setting for supporting off states that the user can toggle?

**Comment by dahlb** [comment]
you can use 1.22.0 likely for a while other then fixes for ha core changes this integration has been very stable.  I'm not interested in supporting a configuration for grey backgrounds that prevent the ui from starting sounds without first turning on a light ... or invoking a media service directly without the help of the default media card, sorry.
