### ISSUE TITLE
Integration does not seem to support Rest+ 2nd Gen

### ISSUE THREAD

**Issue by yuejon** [dahlb/ha_hatch#17]
I understand the integration supports the Rest+ but I believe the it only works with the [1st gen Rest+](https://www.hatch.co/rest-plus) but not the [2nd gen Rest+](https://www.hatch.co/rest-plus-second-gen) . When I add the integration to Home Assistant, it only recognizes my Rest Mini, but not my Rest+ 2nd Gen.

It would be awesome to get it integrated in a future release. Thanks.

**Comment by dahlb** [comment]
thanks those product links helped, I didn't realize I have a 1st gen as I just bought it a few weeks ago.  I don't generally build for features I can't test so I'll leave this open in case another developer wants to add it; or I get a 2nd gen to work with.

**Comment by kmil4** [comment]
I just bought a second gen, didn't check compatibility. Damn.

**Comment by w1ll1am23** [comment]
Trying to work on this here.

https://github.com/dahlb/ha_hatch/pull/25

**Comment by zsarnett** [comment]
Have a BuyMeCoffee, GutHub sponsors or anything that I could contribute to in order to help that support along 😜 (but seriously I actually would donate for the integration)

**Comment by w1ll1am23** [comment]
@zsarnett while the code isn't complete everything posted over in that PR works well enough to get the device in to HA. Feel free to test it out by manually putting those files in the custom components folder.

**Comment by zsarnett** [comment]
On first testing, it seems to work well. Only finicky thing is the turn on and off the media player turns the light off but I think saw you mention something on that

**Comment by w1ll1am23** [comment]
thanks for testing @zsarnett just pushed up some more changes waiting on those to get approved and we can hopefully get this officially added soon. 

The media player stop turning off the light is a real pain, I wish there was a way to fix it easily but without hard coding some random URL for the noSound.wav file there isn't :( and I don't think that is a safe change to make it would break very easy.

**Comment by dahlb** [comment]
merged in
