### ISSUE TITLE
Failed to call service error

### ISSUE THREAD

**Issue by drewancil** [dahlb/ha_hatch#21]
Great integration!  I had been using Homebridge to control a My Rest Mini and was glad to see a native integration.  

I'm getting a an error when controlling the device via the media player (in the frontend UI) or via service call in most instances.  Even though the error message is displayed, the control is successful - the device turns on, and the proper sound that is selected plays.  So although the error message is benign, it makes scripting an extra challenge and of course is confusing in the UI.  The errors break down below:

Controlling the device from:
- From paused->playing - 'Failed to call service: media_player/media_play_pause.
- From playing->paused - No error
- Changing the sound - 'Failed to call service: media_player/select_sound_mode.
- Changing the volume - No error 

I have captured the HA logs after setting custom_components.ha_hatch and hatch_rest_api to debug if they would be helpful.  Let me know how else I can help troubleshoot this issue.

**Comment by dahlb** [comment]
thanks for filing this issue, I've been focused on Rest+ since getting it and missed this; I think I fixed it in 1.9.2

**Comment by drewancil** [comment]
I can confirm it’s fixed and working!   Thanks for the great work.
