### ISSUE TITLE
Unable to install alpine dependency after 1.9.3

### ISSUE THREAD

**Issue by Intecpsp** [dahlb/ha_hatch#23]
After updating to 1.9.3 I now get

```
Unable to install alpine dependency
```

And 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_hatch/__init__.py", line 80, in async_setup_entry
    _lazy_install()
  File "/config/custom_components/ha_hatch/__init__.py", line 69, in _lazy_install
    raise RequirementsNotFound(DOMAIN, [pkg])
homeassistant.requirements.RequirementsNotFound: Requirements for ha_hatch not found: ['hatch-rest-api==1.13.2'].
```

**Comment by Intecpsp** [comment]
I'm comfortable running commands, what do you need me to do?

**Comment by Intecpsp** [comment]
Oddly enough, after updating to 1.9.4 everything is working again. And I can't seem to find any logs saying otherwise.

**Comment by dahlb** [comment]
if you want to get a better error to try to work through and can exec into the ha container, the integration had an error trying to run 
```
apk add gcc g++ cmake make
```
if you run it manually please let me know what the result is

**Comment by Intecpsp** [comment]
I'm not familiar with how to get into the HA containers from the HA CLI. Can you guide me on how to do that?

**Comment by bblicke1** [comment]
Sorry to bring this guy back to life, but I have been having the same issue. I ran the above command in the container console and it seems to have successfully installed the components. However, upon returning to HA and reloading the integration I receive the same error: "Unable to install alpine dependency"

The rest of the error states, "ERROR: Unable to lock database: Permission denied ERROR: Failed to open apk database: Permission denied"

**Comment by dahlb** [comment]
@bblicke1 sounds like you have an unusual ha installation,  since you are running ha with reduced privileges you'll have to install the awscrt pip package yourself or switch to a more typical install like docker or haos

**Comment by dahlb** [comment]
maybe it's you mounts that are causing your issue, what is is saying is 'Failed to open apk database: Permission denied' the user running the ha process is being denied access to the apk install subsystem

**Comment by bblicke1** [comment]
I've now got HA running as root, this is the newest entry in the logs:

Logger: homeassistant.config_entries
Source: .local/lib/python3.10/site-packages/hatch_rest_api/util_bootstrap.py:60
First occurred: 7:53:48 PM (2 occurrences)
Last logged: 8:06:28 PM

Error setting up entry xxxxxxxxxxx@gmail.com for ha_hatch
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_hatch/__init__.py", line 148, in async_setup_entry
    await setup_connection("initial setup")
  File "/config/custom_components/ha_hatch/__init__.py", line 120, in setup_connection
    _, mqtt_connection, rest_devices, expiration_time = await get_rest_devices(
  File "/config/.local/lib/python3.10/site-packages/hatch_rest_api/util_bootstrap.py", line 64, in get_rest_devices
    raise e
  File "/config/.local/lib/python3.10/site-packages/hatch_rest_api/util_bootstrap.py", line 60, in get_rest_devices
    mqtt_connection.connect().result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AWS_ERROR_HTTP_WEBSOCKET_UPGRADE_FAILURE: Failed to upgrade HTTP connection to Websocket.

**Comment by dahlb** [comment]
looks like you're are having firewall issues now, I'm going to lock this conversation as this has all been messaging people from this thread for unrelated issues
