### ISSUE TITLE
Missing media player in Home Assistant

### ISSUE THREAD

**Issue by yuejon** [dahlb/ha_hatch#29]
Hey guys,

Glad to see that issue 17 was closed and support for gen 2 products have been added. However, I just updated to the latest version and now the media player is missing for both my hatch devices (Hatch Rest Mini & Hatch Rest+ Gen 2) in Home Assistant. I'm on the current stable version of Home Assistant (2022.12.8)

Here's the error I found from the logs:

Logger: homeassistant.components.media_player
Source: custom_components/ha_hatch/media_player.py:32
Integration: Media player (documentation, issues)
First occurred: 12:17:07 PM (1 occurrences)
Last logged: 12:17:07 PM

Error while setting up ha_hatch platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ha_hatch/media_player.py", line 32, in async_setup_entry
    media_player_entities = list(map(lambda rest_device: RiotMediaEntity(rest_device) if isinstance(rest_device, RestIot) else RestMediaEntity(rest_device), rest_devices))
  File "/config/custom_components/ha_hatch/media_player.py", line 32, in <lambda>
    media_player_entities = list(map(lambda rest_device: RiotMediaEntity(rest_device) if isinstance(rest_device, RestIot) else RestMediaEntity(rest_device), rest_devices))
TypeError: RestMediaEntity.__init__() missing 1 required positional argument: 'config_turn_on_media'

**Comment by dahlb** [comment]
i have 3 % left on my battery, i pushed a fix that should fix the missing media player for rest plus first gen but will have to follow up when my battery is chargable

**Comment by dahlb** [comment]
looks like it fixed my missing media player, thanks for reporting this so fast and if it is fixed for you too, i'll close this

**Comment by yuejon** [comment]
Works for me now too. Thanks for the quick fix! You can close this.
