### ISSUE TITLE
Toggling the clock in HA causes hatch to revert to non 24hr

### ISSUE THREAD

**Issue by AziwACH** [dahlb/ha_hatch#32]
If you set the clock in the Hatch app to 24hrs display and then toggle the clock button in HA, the clock reverts to not being in 24 hours and you need to into the app to return it to 24hr display

**Comment by dahlb** [comment]
@trevorglaser  @w1ll1am23 ideas on this one?

**Comment by trevorglaser** [comment]
@w1ll1am23 I tested every situation that I could think of (Clock on/off, 24 hr on/off, changed timezone) and everything came back to the flags values listed in my fix. Let me know what you think.

**Comment by w1ll1am23** [comment]
Nice! Yeah I mean that seems like it should work.

**Comment by dahlb** [comment]
@w1ll1am23 can you verify the fix in the api works for you? If so I can bump the dependency version to fix this

**Comment by w1ll1am23** [comment]
I can try to test it later today.

**Comment by w1ll1am23** [comment]
@dahlb looks good to me. 

On and off is working when set to 24 hour mode.

**Comment by dahlb** [comment]
should be fixed in 1.12.3

**Comment by AziwACH** [comment]
tested it. works great. well done and big thank you!
