### ISSUE TITLE
Toddler lock toggle not showing up on Home Assistant for Hatch Rest+ (first generation)

### ISSUE THREAD

**Issue by rml1111** [dahlb/ha_hatch#35]
I have three Rest+'s (two first generation and one second generation). The toddler lock toggle is available for the second generation Rest+ in the HA device screen, however the toddler lock toggle is not displaying for the two first generation Rest+'s. Per the description of this integration the toddler lock toggle is not supported for both generations of the Rest+. Is this a bug, expected behavior, or am I missing something? Thank you for developing this great integration!

**Comment by dahlb** [comment]
this is expected behavior, toddler lock is available for 2nd gen only, first gen toddler lock feature is only available through hatch native scheduled programs.
